=== scalar-labs/scalar-ist/contracts_and_functions/src/main/resources/table/schema/scalar_db_table_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "values": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "bigint",
              "blob",
              "boolean",
              "double",
              "float",
              "int",
              "text"
            ]
          }
        }
      }
    }
  },
  "type": "object",
  "required": [
    "table_name",
    "partition_keys"
  ],
  "properties": {
    "table_name": {
      "type": "string"
    },
    "partition_keys": {
      "$ref": "#/definitions/values"
    },
    "clustering_keys": {
      "$ref": "#/definitions/values"
    },
    "columns": {
      "$ref": "#/definitions/values"
    }
  }
}

=== scalar-labs/scalar-ist/tools/deploy_tool/src/main/resources/schema/table/benefit.json
{
  "$schema": "scalar_db_table_schema.json",
  "table_name": "benefit",
  "partition_keys": [
    {
      "name": "company_id",
      "type": "text"
    }
  ],
  "clustering_keys": [
    {
      "name": "created_at",
      "type": "bigint"
    },
    {
      "name": "organization_id",
      "type": "text"
    }
  ],
  "columns": [
    {
      "name": "category_of_benefit",
      "type": "text"
    },
    {
      "name": "benefit_name",
      "type": "text"
    },
    {
      "name": "description",
      "type": "text"
    },
    {
      "name": "provider",
      "type": "text"
    },
    {
      "name": "time_of_provision",
      "type": "text"
    },
    {
      "name": "updated_at",
      "type": "bigint"
    }
  ]
}

=== scalar-labs/scalar-ist/tools/deploy_tool/src/main/resources/schema/table/data_set_schema.json
{
  "$schema": "scalar_db_table_schema.json",
  "table_name": "data_set_schema",
  "partition_keys": [
    {
      "name": "company_id",
      "type": "text"
    }
  ],
  "clustering_keys": [
    {
      "name": "created_at",
      "type": "bigint"
    },
    {
      "name": "organization_id",
      "type": "text"
    }
  ],
  "columns": [
    {
      "name": "data_set_name",
      "type": "text"
    },
    {
      "name": "description",
      "type": "text"
    },
    {
      "name": "data_location",
      "type": "text"
    },
    {
      "name": "category_of_data",
      "type": "text"
    },
    {
      "name": "data_type",
      "type": "text"
    },
    {
      "name": "classification",
      "type": "text"
    },
    {
      "name": "data_set_schema",
      "type": "text"
    },
    {
      "name": "is_active",
      "type": "boolean"
    },
    {
      "name": "created_by",
      "type": "text"
    },
    {
      "name": "updated_at",
      "type": "bigint"
    }
  ]
}

=== scalar-labs/scalar-ist/contracts_and_functions/src/main/resources/table/schema/purpose.json
{
  "$schema": "scalar_db_table_schema.json",
  "table_name": "purpose",
  "partition_keys": [
    {
      "name": "company_id",
      "type": "text"
    }
  ],
  "clustering_keys": [
    {
      "name": "created_at",
      "type": "bigint"
    },
    {
      "name": "organization_id",
      "type": "text"
    }
  ],
  "columns": [
    {
      "name": "category_of_purpose",
      "type": "text"
    },
    {
      "name": "purpose_name",
      "type": "text"
    },
    {
      "name": "description",
      "type": "text"
    },
    {
      "name": "legal_text",
      "type": "text"
    },
    {
      "name": "user_friendly_text",
      "type": "text"
    },
    {
      "name": "guidance",
      "type": "text"
    },
    {
      "name": "note",
      "type": "text"
    },
    {
      "name": "is_active",
      "type": "boolean"
    },
    {
      "name": "created_by",
      "type": "text"
    },
    {
      "name": "updated_at",
      "type": "bigint"
    }
  ]
}

=== scalar-labs/scalar-ist/tools/deploy_tool/src/main/resources/schema/table/data_retention_policy.json
{
  "$schema": "scalar_db_table_schema.json",
  "table_name": "data_retention_policy",
  "partition_keys": [
    {
      "name": "company_id",
      "type": "text"
    }
  ],
  "clustering_keys": [
    {
      "name": "created_at",
      "type": "bigint"
    },
    {
      "name": "policy_type",
      "type": "text"
    },
    {
      "name": "organization_id",
      "type": "text"
    }
  ],
  "columns": [
    {
      "name": "policy_name",
      "type": "text"
    },
    {
      "name": "length_of_use",
      "type": "text"
    },
    {
      "name": "length_of_retention",
      "type": "text"
    },
    {
      "name": "description",
      "type": "text"
    },
    {
      "name": "is_active",
      "type": "boolean"
    },
    {
      "name": "updated_at",
      "type": "bigint"
    }
  ]
}
