=== scalar-labs/scalar-ist/tools/deploy_tool/src/main/resources/schema/asset/benefit.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "benefit_id": {
      "type": "string",
      "pattern": "asset_id"
    },
    "company_id": {
      "type": "string"
    },
    "organization_id": {
      "type": "string"
    },
    "category_of_benefit": {
      "type": "string"
    },
    "benefit_name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "provider": {
      "type": "string"
    },
    "time_of_provision": {
      "type": "string"
    }
  }
}

=== scalar-labs/scalar-ist/contracts_and_functions/src/test/resources/asset/updated_benefit.json
{
  "company_id": "scalar-labs.com",
  "organization_id": "9ca84f95-2e84-4707-8206-b93c9e78d7b7",
  "category_of_benefit": "sed anim",
  "benefit_name": "dolore magnaxxx",
  "description": "in enim qui dolor",
  "provider": "Duis in",
  "time_of_provision": "reprehenderit nisi nostrud eiusmod ullamco",
  "benefit_id": "benefit-9ca84f95-2e84-4707-8206-b93c9e78d7b7-2"
}

=== scalar-labs/scalar-ist/contracts_and_functions/src/test/resources/asset/sample/benefit.json
{
  "company_id": "scalar-labs.com",
  "organization_id": "org1",
  "category_of_benefit": "sed anim",
  "benefit_name": "dolore magna",
  "description": "in enim qui dolor",
  "provider": "Duis in",
  "time_of_provision": "reprehenderit nisi nostrud eiusmod ullamco",
  "benefit_id": "benefit-org1-1"
}
